seo: 
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  linkedin_url:
  twitter_username: 
design: 
  dark-text_color: '#201E1F'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: '#FCFDFE'
  featured-text_color: '#8A9B68'
  featured_color: '#8A9B68'
  featured-light_color: '#C6CDB5'
  secondary_color: '#FBD799'
  accent_color: '#E38FA3'
  accent-light_color: '#F7DDE2'
  light_color: '#FCFDFE'
  
